CREATE DATABASE customer_behavior;
USE customer_behavior;

SELECT * FROM customer LIMIT 10;

-- Q1)What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount)
AS total_revenue
FROM customer
GROUP BY gender;

-- Q2)Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount 
FROM customer
WHERE discount_applied = TRUE
AND purchase_amount > (SELECT AVG(purchase_amount)
FROM customer);

-- Q3) Which are the top 5 products with the highest average review rating?
SELECT item_purchased, AVG(review_rating) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

-- Q4)Compare the average Purchase Amount between Standard and Express Shipping.
SELECT shipping_type, AVG(purchase_amount)
AS average_purchase_amount
FROM customer
GROUP BY shipping_type;

-- Q5)Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
AVG(purchase_amount) AS average_spend,
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status;

-- Q6)Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
	SUM(CASE WHEN discount_applied = TRUE THEN 1 ELSE 0 END) 
    AS discounted_purchases,
    COUNT(*) AS total_purchases,
    (SUM(CASE WHEN discount_applied = TRUE THEN 1 ELSE 0 END)
    * 100.0/COUNT(*)) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Q7)Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
SELECT
	CASE
		WHEN previous_purchases <= 5
        THEN "New"
        WHEN previous_purchases <= 15
        THEN "Returning"
        ELSE "Loyal"
	END AS customer_segment,
    COUNT(*) AS customer_count
FROM customer
GROUP BY
	CASE
		WHEN previous_purchases <= 5
        THEN "New"
        WHEN previous_purchases <= 15
        THEN "Returning"
        ELSE "Loyal"
	END;

-- Q8)What are the top 3 most purchased products within each category?
SELECT category, item_purchased,
	COUNT(*) AS purchase_count
FROM customer
GROUP BY category, item_purchased;
ROW_NUMBER() OVER(
	PARTION BY category
    ORDER BY purchase_count DESC
)